version: "1"


services:
  app1:
    image: "myapp:2.0"
    container_name: "testDockerAuth"
    build:
      ./
    ports:
      - 5500:5500
  app2:
    image: ""
    container_name: ""
    build:
      ./
    ports:
      - 3000:3000